/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const [active, setActive] = useState(false);
  const { nodes, materials } = useGLTF("/waterdroplet.gltf");

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    group.current.rotation.y = a;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        scale={active ? 1.5 : 1}
        onClick={() => setActive(!active)}
        geometry={nodes.Icosphere.geometry}
        material={materials["Material.002"]}
        position={[0, 1, 0]}
      />
    </group>
  );
}

useGLTF.preload("/waterdroplet.gltf");
